### ISSUE TITLE
Support for other currencies like EUR

### ISSUE THREAD

**Issue by tgy** [arrobalytics/django-ledger#21]
Is it possible to use other currencies than USD?

**Comment by elarroba** [comment]
@tgy Definitely in the road map. Technically the app can support any single-currency since the "$" sign is just the default currency sign. I will accelerate your request to be able to support (or customize) the default currency sign for the next version.
Multi currency support is still in the roadmap.

**Comment by tgy** [comment]
Thanks @elarroba. I have some experience with Django and I really like how this code base looks. I know this is a rather small open-source project (for the moment) but is there an IRC channel or mailing list for developers? I would like to contribute

**Comment by elarroba** [comment]
@tgy Unfortunately I don't have an IRC channel yet, but I will consider that option in the future. 

I have implemented on v0.3.16 a setting to be able to change the default currency symbol via Django settings. Hopefully this will be good enough for now until a more solid currency formatting and multi currency approach is implemented.

If this new functionality is what you are expecting, I will go ahead and close this issue.

I would be happy to onboard you as a contributor, please contact me thru email (found on my public profile) and go from there.

Thank you for your feedback.
