### ISSUE TITLE
DRF integration

### ISSUE THREAD

**Issue by hussamdt** [arrobalytics/django-ledger#58]
Im planning to use the django ledger in my lease and property management system using django rest framework as backend and next.js standalone as front end

But i found it hard to understand the code since i noticed there are not comments on code

Any clear documentation for models since i plan to use it with django rest framework so i need to understand the code rather than use it
If any commented code or docs im interested to join the team

Best regards

**Comment by elarroba** [comment]
@hussamdt Documentation is part of the ROADMAP. Unfortunately due to limited resources the project is mostly focused on new features. There is a documentation module already setup using Sphinx (/docs), however, code base needs to be documented.

If you are interested in contributing to documentation, documenting Models and Views is a good place to start.
Thank you for your interested in contributing.

**Comment by hussamdt** [comment]
@elarroba thank you,
Sure im interested, i will try to spare some time for that

**Comment by Mzekri-madar** [comment]
Hello @hussamdt did you find a way to successfully integrate ledger into you application?

**Comment by hussamdt** [comment]
@Mzekri-madar actually not, i ended up writing my own models for finance purpose, since my need is simple not that complex finance transactions, django-ledger is seems nice but lack in documentation, so cannot understand the models structure

**Comment by elarroba** [comment]
A new pull request has been initiated add GraphQL api functionality to the project.
You may want to check it out and if possible please contribute.
Thanks
